/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel_Person */

#ifndef _Included_com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel_Person
#define _Included_com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel_Person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel_Person
 * Method:    persistToDisk
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel_00024Person_persistToDisk
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
