/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel */

#ifndef _Included_com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel
#define _Included_com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel
 * Method:    getAllPersons
 * Signature: ()[Lcom/mobconverge/CrossPlatformTutorial/model/CrossPlatformTutorialModel/Person;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mobconverge_CrossPlatformTutorial_model_CrossPlatformTutorialModel_getAllPersons
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
